# Generated by Django 2.0.4 on 2018-05-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=128)),
                ('due', models.CharField(max_length=64)),
                ('period', models.CharField(max_length=64)),
                ('due_flag', models.CharField(max_length=16)),
                ('identify', models.CharField(max_length=512, unique=True)),
                ('site', models.CharField(max_length=64)),
                ('save_date', models.DateTimeField()),
                ('vis', models.BooleanField()),
                ('fav', models.BooleanField()),
            ],
        ),
    ]
