# Generated by Django 2.0.4 on 2018-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appstore_crawler', '0004_auto_20180430_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=16)),
                ('icon_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AppImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=16)),
                ('img_url_0', models.CharField(max_length=512)),
                ('img_url_1', models.CharField(max_length=512)),
                ('img_url_2', models.CharField(max_length=512)),
                ('img_url_3', models.CharField(max_length=512)),
                ('img_url_4', models.CharField(max_length=512)),
                ('img_url_5', models.CharField(max_length=512)),
                ('img_url_6', models.CharField(max_length=512)),
                ('img_url_7', models.CharField(max_length=512)),
                ('img_url_8', models.CharField(max_length=512)),
                ('img_url_9', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=16)),
                ('lang', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=16)),
                ('author', models.CharField(max_length=16)),
                ('rating', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=512)),
            ],
        ),
    ]
