# Generated by Django 2.0.4 on 2018-04-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore_crawler', '0006_auto_20180430_0334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AoppstoreCrawler',
            new_name='AppstoreCrawler',
        ),
    ]
