# Generated by Django 2.0.4 on 2018-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore_crawler', '0007_auto_20180430_0347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppIcon',
        ),
        migrations.RemoveField(
            model_name='appimage',
            name='id',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='icon_url',
            field=models.CharField(default='www', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appimage',
            name='app_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
