# Generated by Django 2.0.4 on 2018-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore_crawler', '0008_auto_20180430_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='app_rating',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
