# Generated by Django 2.0.4 on 2018-04-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('due', models.CharField(max_length=32)),
                ('identify', models.CharField(max_length=512, unique=True)),
                ('site', models.CharField(max_length=64)),
                ('save_date', models.DateTimeField()),
                ('vis', models.BooleanField()),
                ('fav', models.BooleanField()),
            ],
        ),
    ]
