# Generated by Django 2.0.4 on 2018-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='due_flag',
            field=models.CharField(default='def', max_length=16),
            preserve_default=False,
        ),
    ]
